### ISSUE TITLE
Allow `<` followed by whitespace as markdown instead of JSX

### ISSUE THREAD

**Issue by wooorm** [micromark/micromark-extension-mdx-jsx#7]
### Subject of the feature

JSX allows arbitrary whitespace: `< x / >`. `<` is a character frequently used in markdown.
As HTML does not allow it, formatters (prettier) don’t print it, and it’s a style I haven’t seen authors use, we should deviate from JSX here and treat the `<` followed by `[ \t\r\n]` as a lone `<` instead of a JSX opening.
I do think any other character (e.g., `<1` or `<-`) should still crash, as there it’s not as clear.

/cc @jescalan

**Comment by wooorm** [comment]
Hmm, not too sure about this:

```
a < >b</>
a <>b< />
a <
b>c</b>
a <b>c< /b>
```

While they look a bit weird, they also look valid, and this would break them.

**Comment by ChristianMurphy** [comment]
```html
a <>b< />
a <b>c< /b>
```

these tow specifically, I'd tend to interpret as JSX over markdown.
I have seen code styles which tend to put a space in closing/self closing tags `</ b>` and `<br />`.
However I get the consistency argument to not count them as JSX.

**Comment by wooorm** [comment]
Indeed.

The `</ b>` and `<br />` cases will be fine! Tthis change is specifically `<` + `[ \t\r\n]` no longer seen as JSX, `<` + anything else will still be seen as JSX (and parse / potentially crash)

**Comment by wooorm** [comment]
[Released](https://github.com/micromark/micromark-extension-mdx-jsx/releases/tag/0.3.2)!
